from typing import Mapping
from class_id import mid, MsgClass, NavID, RxmID, MonID

GEN7_PATCH: Mapping[int, dict] = {
    mid(MsgClass.NAV, NavID.SOL): dict(
        hdr_fix=(
            "iTOW (ms)",
            "fTOW (ns)",
            "week (weeks)",
            "gpsFix",
            "flags",
            "ecefX (cm)",
            "ecefY (cm)",
            "ecefZ (cm)",
            "pAcc (cm)",
            "ecefVX (cm/s)",
            "ecefVY (cm/s)",
            "ecefVZ (cm/s)",
            "sAcc (cm/s)",
            "pDOP",
            "reserved1",
            "numSV",
            "reserved2",
        ),
    ),
    mid(MsgClass.NAV, NavID.PVT): dict(
        name="nav_pvt",
        payload_len_fix=84,
        fmt_fix="U4U2U1U1U1U1U1X1U4I4U1X1U1U1I4I4I4I4U4U4I4I4I4I4I4U4U4U2X2U4",
        scale_fix=(
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1e-7,
            1e-7,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1e-5,
            1,
            1e-5,
            0.01,
            1,
            1,
        ),
        hdr_fix=(
            "iTOW (ms)",
            "year (y)",
            "month (month)",
            "day (d)",
            "hour (h)",
            "min (min)",
            "sec (s)",
            "valid",
            "tAcc (ns)",
            "nano (ns)",
            "fixType",
            "flags",
            "reserved1",
            "numSV",
            "lon (deg)",
            "lat (deg)",
            "height (mm)",
            "hMSL (mm)",
            "hAcc (mm)",
            "vAcc (mm)",
            "velN (mm/s)",
            "velE (mm/s)",
            "velD (mm/s)",
            "gSpeed (mm/s)",
            "heading (deg)",
            "sAcc (mm/s)",
            "headingAcc (deg)",
            "pDOP",
            "reserved2",
            "reserved3",
        ),
    ),
    mid(MsgClass.NAV, NavID.DGPS): dict(fmt_var="U1X1U2R4R4"),
    mid(MsgClass.NAV, NavID.AOPSTATUS): dict(
        hdr_fix=(
            "iTOW (ms)",
            "aopCfg",
            "status",
            "reserved0",
            "reserved1",
            "availGPS",
            "reserved2",
            "reserved3",
        )
    ),
    mid(MsgClass.RXM, RxmID.RAW): dict(
        hdr_fix=("rcvTow (ms)", "week (weeks)", "numSV", "reserved1")
    ),
    mid(MsgClass.RXM, RxmID.SVSI): dict(fmt_fix="U4I2U1U1"),
    mid(MsgClass.MON, MonID.HW): dict(
        payload_len_fix=60,
        fmt_fix="X4X4X4X4U2U2U1U1X1U1X4" + "U1" * 17 + "U1U2X4X4X4",
        scale_fix=(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1) + (1,) * 17 + (1, 1, 1, 1, 1),
        hdr_fix=(
            "pinSel",
            "pinBank",
            "pinDir",
            "pinVal",
            "noisePerMS",
            "agcCnt",
            "aStatus",
            "aPower",
            "flags",
            "reserved1",
            "usedMask",
        )
        + ("VP",) * 17
        + ("jamInd", "reserved3", "pinIrq", "pullH", "pullL"),
    ),
    mid(MsgClass.MON, MonID.HW2): dict(
        fmt_fix="I1U1I1U1U1" + "U1" * 3 + "U4" + "U4" * 2 + "U4U4"
    ),
}
